import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

st.header("Airbnb site hotel")
df = pd.read_csv("Airbnb_site_hotel new.csv")

st.write("To understand which data are harder to collect, we will first identify the most challenging ones.")
df_na = df.isna().sum()
fig1, ax1 = plt.subplots()
ax1.barh(df_na.index, df_na.values, color='skyblue')
ax1.set_xlabel("Missing Data Columns")
ax1.tick_params(axis='x', rotation=75)
plt.tight_layout()
st.pyplot(fig1)

st.write("This chart displays the number of Airbnb listings in each city.")
fig2, ax2 = plt.subplots()
ax2.bar(df['city'].value_counts().index, df['city'].value_counts().values)
ax2.set_xlabel("City")
ax2.set_ylabel("Count")
ax2.set_title("Number of Listings per City")
plt.xticks(rotation=45)
plt.tight_layout()
st.pyplot(fig2)

st.write("This chart displays the average price in each city.")
df['price'] = pd.to_numeric(df['price'], errors='coerce')
city_average_price = df.groupby('city')['price'].mean()
fig3, ax3 = plt.subplots()
ax3.bar(city_average_price.index, city_average_price.values)
ax3.set_xlabel("City")
ax3.set_ylabel("price")
ax3.set_title("Average price in each city")
plt.xticks(rotation=45)
plt.tight_layout()
st.pyplot(fig3)

st.write("This chart displays the number of host in each city.")
df['price'] = pd.to_numeric(df['price'], errors='coerce')
city_host_number = df.groupby('city')['host_name'].nunique()
fig4, ax4 = plt.subplots()
ax4.bar(city_host_number.index, city_host_number.values)
ax4.set_xlabel("City")
ax4.set_ylabel("price")
ax4.set_title("Number of host in each city")
plt.xticks(rotation=45)
plt.tight_layout()
st.pyplot(fig4)

st.write("This chart shows the distribution of hosts across different areas.")
areas = df['area'].value_counts()
fig5, ax5 = plt.subplots()
ax5.pie(areas.values, labels=areas.index, autopct='%1.1f%%')
ax5.set_title("Proportion of Hosts by Area")
plt.xticks(rotation=45)
plt.tight_layout()
st.pyplot(fig5)

st.write("This scatter plot shows the relationship between guest ratings and listing prices.")
df['sales'] = pd.to_numeric(df['sales'], errors='coerce')
df_scatter = df[['price', 'sales']].dropna()
df = df[(df['price'] >= 10) & (df['price'] <= 1000)]
df = df[(df['sales'] >= 0) & (df['sales'] <= 400)]
fig6, ax6 = plt.subplots()
ax6.scatter(df_scatter['price'], df_scatter['sales'], alpha=0.5)
ax6.set_title("Price vs. Guest Ratings")
ax6.set_xlabel("Price")
ax6.set_ylabel("Guest Ratings")
plt.xticks(rotation=45)
plt.tight_layout()
st.pyplot(fig6)
